apiVersion: v1
kind: Service
metadata:
  name: api-devops-demo
  namespace: default
  labels:
    app: api-devops-demo
spec:
  type: NodePort
  selector:
    app: api-devops-demo
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
